Fixed YAML syntax errors

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,13 +6,7 @@ script:
 - RETURNED=$(java -jar ckbuilder.jar --no-ie-checks --verify-plugin 1ckeditor-ruler.zip)
 - EXPECTED="OK"
 - java -jar ckbuilder.jar --no-ie-checks --verify-plugin ckeditor-ruler.zip
-- 'if [ \'$RETURNED\' = \'$EXPECTED\' ]
-    then
-        echo -e \'\e[42mTests PASSED\e[0m\'
-    else
-        echo -e \'\e[41mTests FAILED\e[0m\'
-    exit 1
-  fi'
+- if [ "$RETURNED" = "$EXPECTED" ]; then echo -e "\e[42mTests PASSED\e[0m"; else echo -e "\e[41mTests FAILED\e[0m" exit 1; fi
 deploy:
   provider: releases
   api_key:
