Fixed vars comparison in build script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,15 +3,15 @@ install:
 - wget http://download.cksource.com/CKBuilder/2.3.1/ckbuilder.jar
 script:
 - zip -r ckeditor-ruler ./ -x docs/\* -x .git/\* -x .gitignore -x .npmignore -x .travis.yml
-- RESULT=$(java -jar ckbuilder.jar --no-ie-checks --verify-plugin ckeditor-ruler.zip)
+- EXPECTED="OK"
 - java -jar ckbuilder.jar --no-ie-checks --verify-plugin ckeditor-ruler.zip
-- if [ $RESULT == 'OK' ];
-      then
-          echo -e '\e[42mTest passed!\e[42m'
-      else
-          echo -e '\e[41mTest failed!\e[41m'
-          exit 1
-  fi
+- if [ "$RETURNED" = "$EXPECTED" ]
+-    then
+-        echo -e "\e[42mTests PASSED\e[0m"
+    else
+        echo -e "\e[41mTests FAILED\e[0m"
+        exit 1
+fi
 
 deploy:
   provider: releases
